In [20]:
from tensorflow.keras.preprocessing.text import one_hot


In [22]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocabulary size
voc_size = 10000

In [25]:
## One Hot Representation
one_hot_rep = [one_hot(words,voc_size)for words in sent]
one_hot_rep 


[[2837, 5310, 9784, 2367],
 [2837, 5310, 9784, 2198],
 [2837, 21, 9784, 2839],
 [3005, 9573, 2985, 8774, 8942],
 [3005, 9573, 2985, 8774, 7131],
 [8463, 2837, 6160, 9784, 2227],
 [3375, 8902, 3340, 8774]]

In [26]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential



In [27]:
import numpy as np

In [28]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2837 5310 9784 2367]
 [   0    0    0    0 2837 5310 9784 2198]
 [   0    0    0    0 2837   21 9784 2839]
 [   0    0    0 3005 9573 2985 8774 8942]
 [   0    0    0 3005 9573 2985 8774 7131]
 [   0    0    0 8463 2837 6160 9784 2227]
 [   0    0    0    0 3375 8902 3340 8774]]


In [29]:
## Feature representation
dim=10

In [30]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')


In [31]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.04639047,  0.01462201,  0.00165074,  0.04398758,
          0.01915479,  0.00016925,  0.00983065,  0.03787564,
          0.00704337,  0.02967614],
        [-0.02136453, -0.01052468, -0.01459522, -0.04762828,
          0.03695888,  0.0318994 , -0.02313756,  0.04240087,
          0.02063458,  0.04919911],
        [ 0.01852072, -0.01625128, -0.01662331,  0.0

In [33]:
embedded_docs[0]

array([   0,    0,    0,    0, 2837, 5310, 9784, 2367], dtype=int32)

In [35]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.03684766,  0.0317695 , -0.03408079,  0.0385148 ,
         -0.02074426, -0.04540702,  0.03940663,  0.02365721,
         -0.02825316, -0.00237088],
        [-0.04639047,  0.01462201,  0.00165074,  0.04398758,
          0.01915479,  0.00016925,  0.00983065,  0.03787564,
          0.00704337,  0.02967614],
        [-0.02136453, -0.01052468, -0.01459522, -0.04762828,
          0.03695888,  0.0318994 , -0.02313756,  0.04240087,
          0.02063458,  0.04919911],
        [ 0.01852072, -0.01625128, -0.01662331,  0.0